### ISSUE TITLE
Project Completion Checklist

### ISSUE THREAD

**Issue by zakariyeali** [cscm94go/CSCM94Go#10]
**1.1 Users:**
- [x] Users
- [x] Admin

**1.2 Game 'Go':**
- [x] GameController
- [x] GameClasses
- [x] GameBoard

**1.3 Information Since Last Login:**
- [x] Games that have been completed since last login
- [x] Changes to user position in leaderboard
- [x] New players that have been added (by Admin)

**1.4 Profile Images**
- [x] Users have and can select their own profile images on register
- [ ] **enhancement** --> Users can change their profile image via menu on dashboard

**1.5 Player Records:**
- [x] System can track wins and losses of each player and admin and use on leaderboard

**1.6 User Dashboard AKA 'My Record' page:**
- [x]  History of all results the games a player has played in chronological order
- [x]  Display the users win percentage on this page

 - [x] **JAVADOCS FOR ALL CLASSES AND CONTROLLERS** 

> Your application should be fully documented with Javadoc as per the
coding conventions in Lecture 13 (Coding Conventions). Please also see Lecture 16 (Javadoc).
A copy of the website produced by Javadoc (all files produced) must be included in a folder
named “doc” within your “GroupGN-Cwk3” folder

- [x] **VIDEO DEMO** 
> You must create a video that demonstrates the features of your
application. You could use screen capturing software to do this. The audio or subtitles should
2
clearly explain what is happening in the video

- [x] **MINUTES PROTOCOL** 
> (A copy of your group minutes for three (or more) meetings held before
the assignment deadline must be included in your submission to Blackboard. Your minutes
files must be names “GroupGNMinutes-yyyy-mm-dd.txt”)

- [x] **CONTRIBUTIONS REPORT**
> (The file must be named “GroupGNMemberContributions.pdf”
> where GN is replaced by your group number)

**Comment by zakariyeali** [comment]
Complete
